version: '3.8'

# Test configuration for CI/CD
services:
  borlacam-api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - FLASK_ENV=production
      - ALLOWED_ORIGINS=*
    volumes:
      - ./logs:/app/logs
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s